/**
 * IMAGINE-MANAGED FILE.
 * Do not edit this file manually or with AI.
 * Update Website Info from the Imagine Studio settings.
 * Changes may be overwritten by Imagine.
 */

export type WebsiteInfo = {
  title: string | null;
  description: string | null;
  faviconUrl: string | null;
  ogImageUrl: string | null;
};

export const websiteInfo: WebsiteInfo = {
  title: "Imagine App",
  description: null,
  faviconUrl: null,
  ogImageUrl: null,
};
